application: track-on
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: src/main.py

- url: /test
  script: src/test.py

- url: /static/
  static_dir: static

- url: /favicon.ico
  static_files: static/imgs/favicon.ico
  upload: static/imgs/favicon.ico

- url: /_ah/queue/new-trackers
  script: src/new-trackers.py
  login: admin # Dev server is broken

- url: /_ah/queue/update-trackers
  script: src/update-trackers.py
  login: admin

- url: /app-admin/
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /google1c5d509bd1822f1d.html
  static_files: static/null.html
  upload: static/null.html

#- url: /.*
#  script: 404.py


