application: track-on
version: 2
runtime: python
api_version: 1

handlers:

- url: /
  script: trackon/main.py

- url: /incoming-log
  script: trackon/incoming-log.py

- url: /trackers-raw-info
  script: trackon/trackers-raw-info.py

- url: /admin
  script: trackon/admin.py
  login: admin

# Api
- url: /api/live
  script: trackon/api/live.py


# Static stuff
- url: /static/
  static_dir: static

- url: /(api-docs|faq)
  static_files: static/\1.html
  upload: static/(.*).html

- url: /favicon.ico
  static_files: static/imgs/favicon.ico
  upload: static/imgs/favicon.ico

- url: /_ah/queue/new-trackers
  script: trackon/new-trackers.py
  #login: admin # Dev server is broken

- url: /_ah/queue/update-trackers
  script: trackon/update-trackers.py
  #login: admin

- url: /app-admin/
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /google1c5d509bd1822f1d.html
  static_files: static/null.html
  upload: static/null.html

#- url: /.*
#  script: 404.py


